apiVersion: v1
kind: Pod
metadata:
  name: mapd
  labels:
    app: mapd
spec:
  nodeSelector:
    nodetype: cpu
  containers:
  - name: mapd
    image: mapd/mapd-ce-cpu
    volumeMounts:
    - mountPath: "/mapd-storage"
      name: mystor
    ports:
    -name: mapd-port0
    containerPort: 9090
    -name: mapd-port1
    containerPort: 9091
    -name: mapd-port2
    containerPort: 9092
  volumes:
    - name: mystor
      nfs:
        server: fs-2bc69063.efs.us-east-1.amazonaws.com
        path: /
